name: Daily Script Run

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install scratch-websocket-api websocket-client requests

      - name: Debug Environment Variables
        run: echo "SCRATCH_ID=${{ secrets.SUID }}" && echo "SCRATCH_PASSWORD=***"

      - name: Run script
        env:
          SCRATCH_ID: ${{ secrets.SUID }}
          SCRATCH_PASSWORD: ${{ secrets.SUPS }}
        run: python api.py
